sudo: false
language: python
python:
  - "3.6"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE meier;'
install: pip install -r ./requirements
script:
  - pytest -s --cov=codecov
after_success:
  - codecov
notifications:
  slack: ash84:XLALpV0b20grjYRBYJ9ooVaE
